name: nyt
channels:
  - conda-forge
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2023.5.7
  - libexpat=2.5.0
  - libffi=3.4.2
  - libsqlite=3.42.0
  - libzlib=1.2.13
  - ncurses=6.4
  - openssl=3.1.1
  - pip=23.1.2
  - python=3.11.3
  - readline=8.2
  - setuptools=67.7.2
  - tk=8.6.12
  - tzdata=2023c
  - wheel=0.40.0
  - xz=5.2.6
  - pip:
      - beautifulsoup4==4.12.2
      - certifi==2023.5.7
      - charset-normalizer==3.1.0
      - clean-text==0.6.0
      - emoji==1.7.0
      - ftfy==6.1.1
      - idna==3.4
      - requests==2.31.0
      - soupsieve==2.4.1
      - urllib3==2.0.3
      - wcwidth==0.2.6
